const http = require('node:http');
const fs = require('node:fs');
const path = require('node:path');

const PORT = 3001;
const ROOT = path.resolve(__dirname, '..');
const tokenCssPath = path.join(ROOT, 'browser-demo', 'design-tokens.css');
const tokenJsonPath = path.join(ROOT, 'browser-demo', 'design-tokens.json');

const defaultPayload = {
  source: 'default',
  component: 'TerminCard',
  activeStatus: 'available',
  tokens: {
    available: { bg: '#DFF7E8', text: '#126B3A', border: '#8ED9AC' },
    waitlist: { bg: '#FFF0C2', text: '#7A4B00', border: '#F5D36B' },
    full: { bg: '#F3F4F6', text: '#6B7280', border: '#D1D5DB' }
  },
  layout: { radius: 18, padding: 18, gap: 12 },
  generatedAt: new Date().toISOString()
};

function withCors(res, status, type = 'application/json') {
  res.writeHead(status, {
    'Content-Type': type,
    'Access-Control-Allow-Origin': '*',
    'Access-Control-Allow-Methods': 'GET,POST,OPTIONS',
    'Access-Control-Allow-Headers': 'Content-Type',
    'Cache-Control': 'no-store, no-cache, must-revalidate, proxy-revalidate',
    'Pragma': 'no-cache',
    'Expires': '0'
  });
}
function send(res, status, body, type = 'application/json') {
  withCors(res, status, type);
  res.end(type === 'application/json' ? JSON.stringify(body, null, 2) : body);
}
function readBody(req) {
  return new Promise((resolve, reject) => {
    let data = '';
    req.on('data', chunk => data += chunk);
    req.on('end', () => resolve(data));
    req.on('error', reject);
  });
}
function cssFromTokens(payload) {
  const t = payload.tokens;
  return `/* Generated by the TerminCard Figma Live Bridge. */\n:root {\n  --status-available-bg: ${t.available.bg};\n  --status-available-text: ${t.available.text};\n  --status-available-border: ${t.available.border};\n\n  --status-waitlist-bg: ${t.waitlist.bg};\n  --status-waitlist-text: ${t.waitlist.text};\n  --status-waitlist-border: ${t.waitlist.border};\n\n  --status-full-bg: ${t.full.bg};\n  --status-full-text: ${t.full.text};\n  --status-full-border: ${t.full.border};\n\n  --card-radius: ${payload.layout.radius}px;\n  --card-padding: ${payload.layout.padding}px;\n  --card-gap: ${payload.layout.gap}px;\n}\n`;
}
function ensureFiles() {
  if (!fs.existsSync(tokenJsonPath)) {
    fs.writeFileSync(tokenJsonPath, JSON.stringify(defaultPayload, null, 2), 'utf8');
  }
  if (!fs.existsSync(tokenCssPath)) {
    fs.writeFileSync(tokenCssPath, cssFromTokens(defaultPayload), 'utf8');
  }
}
function readTokens() {
  ensureFiles();
  try { return JSON.parse(fs.readFileSync(tokenJsonPath, 'utf8')); }
  catch { return defaultPayload; }
}
function validatePayload(payload) {
  if (!payload || !payload.tokens || !payload.layout) throw new Error('Missing tokens or layout');
  for (const status of ['available', 'waitlist', 'full']) {
    for (const key of ['bg', 'text', 'border']) {
      if (!payload.tokens[status] || typeof payload.tokens[status][key] !== 'string') throw new Error(`Missing token ${status}.${key}`);
    }
  }
}

ensureFiles();

const server = http.createServer(async (req, res) => {
  if (req.method === 'OPTIONS') return send(res, 200, { ok: true });

  if (req.method === 'GET' && req.url === '/health') {
    return send(res, 200, { ok: true, message: 'TerminCard bridge server is running', cssFile: tokenCssPath, jsonFile: tokenJsonPath });
  }

  if (req.method === 'GET' && req.url.startsWith('/tokens')) {
    return send(res, 200, { ok: true, payload: readTokens() });
  }

  if (req.method === 'POST' && req.url === '/sync-tokens') {
    try {
      const raw = await readBody(req);
      const payload = JSON.parse(raw);
      validatePayload(payload);
      payload.generatedAt = new Date().toISOString();
      fs.writeFileSync(tokenCssPath, cssFromTokens(payload), 'utf8');
      fs.writeFileSync(tokenJsonPath, JSON.stringify(payload, null, 2), 'utf8');
      console.log(`[sync] ${payload.component || 'component'} ${payload.activeStatus || ''} -> ${tokenCssPath}`);
      return send(res, 200, { ok: true, message: 'Synced Figma tokens to browser-demo/design-tokens.css and design-tokens.json', activeStatus: payload.activeStatus, generatedAt: payload.generatedAt });
    } catch (error) {
      return send(res, 400, { ok: false, error: error.message });
    }
  }

  send(res, 404, { ok: false, error: 'Not found' });
});

server.listen(PORT, 'localhost', () => {
  console.log(`TerminCard bridge server running at http://localhost:${PORT}`);
  console.log(`Health check: http://localhost:${PORT}/health`);
  console.log(`Live token endpoint: http://localhost:${PORT}/tokens`);
});
